export type Instrument = {
  symbol: string;
  tradingSymbol: string;
  exchange: "NSE" | "BSE";
  token: string;
  name: string;
};

export const INSTRUMENTS: Record<string, Instrument> = {
  ADANIENT: {
    symbol: "ADANIENT",
    tradingSymbol: "ADANIENT-EQ",
    exchange: "NSE",
    token: "25",
    name: "Adani Enterprises",
  },
  ADANIPORTS: {
    symbol: "ADANIPORTS",
    tradingSymbol: "ADANIPORTS-EQ",
    exchange: "NSE",
    token: "15083",
    name: "Adani Ports and SEZ",
  },
  APOLLOHOSP: {
    symbol: "APOLLOHOSP",
    tradingSymbol: "APOLLOHOSP-EQ",
    exchange: "NSE",
    token: "157",
    name: "Apollo Hospitals",
  },
  ASIANPAINT: {
    symbol: "ASIANPAINT",
    tradingSymbol: "ASIANPAINT-EQ",
    exchange: "NSE",
    token: "236",
    name: "Asian Paints",
  },
  AXISBANK: {
    symbol: "AXISBANK",
    tradingSymbol: "AXISBANK-EQ",
    exchange: "NSE",
    token: "5900",
    name: "Axis Bank",
  },
  "BAJAJ-AUTO": {
    symbol: "BAJAJ-AUTO",
    tradingSymbol: "BAJAJ-AUTO-EQ",
    exchange: "NSE",
    token: "16669",
    name: "Bajaj Auto",
  },
  BAJFINANCE: {
    symbol: "BAJFINANCE",
    tradingSymbol: "BAJFINANCE-EQ",
    exchange: "NSE",
    token: "317",
    name: "Bajaj Finance",
  },
  BAJAJFINSV: {
    symbol: "BAJAJFINSV",
    tradingSymbol: "BAJAJFINSV-EQ",
    exchange: "NSE",
    token: "16675",
    name: "Bajaj Finserv",
  },
  BEL: {
    symbol: "BEL",
    tradingSymbol: "BEL-EQ",
    exchange: "NSE",
    token: "383",
    name: "Bharat Electronics",
  },
  BHARTIARTL: {
    symbol: "BHARTIARTL",
    tradingSymbol: "BHARTIARTL-EQ",
    exchange: "NSE",
    token: "10604",
    name: "Bharti Airtel",
  },
  BPCL: {
    symbol: "BPCL",
    tradingSymbol: "BPCL-EQ",
    exchange: "NSE",
    token: "526",
    name: "Bharat Petroleum",
  },
  BRITANNIA: {
    symbol: "BRITANNIA",
    tradingSymbol: "BRITANNIA-EQ",
    exchange: "NSE",
    token: "547",
    name: "Britannia Industries",
  },
  CIPLA: {
    symbol: "CIPLA",
    tradingSymbol: "CIPLA-EQ",
    exchange: "NSE",
    token: "694",
    name: "Cipla",
  },
  COALINDIA: {
    symbol: "COALINDIA",
    tradingSymbol: "COALINDIA-EQ",
    exchange: "NSE",
    token: "20374",
    name: "Coal India",
  },
  DRREDDY: {
    symbol: "DRREDDY",
    tradingSymbol: "DRREDDY-EQ",
    exchange: "NSE",
    token: "881",
    name: "Dr. Reddy's Laboratories",
  },
  EICHERMOT: {
    symbol: "EICHERMOT",
    tradingSymbol: "EICHERMOT-EQ",
    exchange: "NSE",
    token: "910",
    name: "Eicher Motors",
  },
  GRASIM: {
    symbol: "GRASIM",
    tradingSymbol: "GRASIM-EQ",
    exchange: "NSE",
    token: "1232",
    name: "Grasim Industries",
  },
  HCLTECH: {
    symbol: "HCLTECH",
    tradingSymbol: "HCLTECH-EQ",
    exchange: "NSE",
    token: "7229",
    name: "HCL Technologies",
  },
  HDFCBANK: {
    symbol: "HDFCBANK",
    tradingSymbol: "HDFCBANK-EQ",
    exchange: "NSE",
    token: "1333",
    name: "HDFC Bank",
  },
  HDFCLIFE: {
    symbol: "HDFCLIFE",
    tradingSymbol: "HDFCLIFE-EQ",
    exchange: "NSE",
    token: "467",
    name: "HDFC Life Insurance",
  },
  HEROMOTOCO: {
    symbol: "HEROMOTOCO",
    tradingSymbol: "HEROMOTOCO-EQ",
    exchange: "NSE",
    token: "1348",
    name: "Hero MotoCorp",
  },
  HINDALCO: {
    symbol: "HINDALCO",
    tradingSymbol: "HINDALCO-EQ",
    exchange: "NSE",
    token: "1363",
    name: "Hindalco Industries",
  },
  HINDUNILVR: {
    symbol: "HINDUNILVR",
    tradingSymbol: "HINDUNILVR-EQ",
    exchange: "NSE",
    token: "1394",
    name: "Hindustan Unilever",
  },
  ICICIBANK: {
    symbol: "ICICIBANK",
    tradingSymbol: "ICICIBANK-EQ",
    exchange: "NSE",
    token: "4963",
    name: "ICICI Bank",
  },
  INDUSINDBK: {
    symbol: "INDUSINDBK",
    tradingSymbol: "INDUSINDBK-EQ",
    exchange: "NSE",
    token: "5258",
    name: "IndusInd Bank",
  },
  INFY: {
    symbol: "INFY",
    tradingSymbol: "INFY-EQ",
    exchange: "NSE",
    token: "1594",
    name: "Infosys",
  },
  ITC: {
    symbol: "ITC",
    tradingSymbol: "ITC-EQ",
    exchange: "NSE",
    token: "1660",
    name: "ITC",
  },
  JSWSTEEL: {
    symbol: "JSWSTEEL",
    tradingSymbol: "JSWSTEEL-EQ",
    exchange: "NSE",
    token: "11723",
    name: "JSW Steel",
  },
  KOTAKBANK: {
    symbol: "KOTAKBANK",
    tradingSymbol: "KOTAKBANK-EQ",
    exchange: "NSE",
    token: "1922",
    name: "Kotak Mahindra Bank",
  },
  LT: {
    symbol: "LT",
    tradingSymbol: "LT-EQ",
    exchange: "NSE",
    token: "11483",
    name: "Larsen & Toubro",
  },
  "M&M": {
    symbol: "M&M",
    tradingSymbol: "M&M-EQ",
    exchange: "NSE",
    token: "2031",
    name: "Mahindra & Mahindra",
  },
  MARUTI: {
    symbol: "MARUTI",
    tradingSymbol: "MARUTI-EQ",
    exchange: "NSE",
    token: "10999",
    name: "Maruti Suzuki",
  },
  NESTLEIND: {
    symbol: "NESTLEIND",
    tradingSymbol: "NESTLEIND-EQ",
    exchange: "NSE",
    token: "17963",
    name: "Nestle India",
  },
  NTPC: {
    symbol: "NTPC",
    tradingSymbol: "NTPC-EQ",
    exchange: "NSE",
    token: "11630",
    name: "NTPC",
  },
  ONGC: {
    symbol: "ONGC",
    tradingSymbol: "ONGC-EQ",
    exchange: "NSE",
    token: "2475",
    name: "Oil and Natural Gas Corporation",
  },
  POWERGRID: {
    symbol: "POWERGRID",
    tradingSymbol: "POWERGRID-EQ",
    exchange: "NSE",
    token: "14977",
    name: "Power Grid Corporation",
  },
  RELIANCE: {
    symbol: "RELIANCE",
    tradingSymbol: "RELIANCE-EQ",
    exchange: "NSE",
    token: "2885",
    name: "Reliance Industries",
  },
  SBILIFE: {
    symbol: "SBILIFE",
    tradingSymbol: "SBILIFE-EQ",
    exchange: "NSE",
    token: "21808",
    name: "SBI Life Insurance",
  },
  SBIN: {
    symbol: "SBIN",
    tradingSymbol: "SBIN-EQ",
    exchange: "NSE",
    token: "3045",
    name: "State Bank of India",
  },
  SHRIRAMFIN: {
    symbol: "SHRIRAMFIN",
    tradingSymbol: "SHRIRAMFIN-EQ",
    exchange: "NSE",
    token: "4306",
    name: "Shriram Finance",
  },
  SUNPHARMA: {
    symbol: "SUNPHARMA",
    tradingSymbol: "SUNPHARMA-EQ",
    exchange: "NSE",
    token: "3351",
    name: "Sun Pharmaceutical",
  },
  TATACONSUM: {
    symbol: "TATACONSUM",
    tradingSymbol: "TATACONSUM-EQ",
    exchange: "NSE",
    token: "3432",
    name: "Tata Consumer Products",
  },
  TATAMOTORS: {
    symbol: "TATAMOTORS",
    tradingSymbol: "TATAMOTORS-EQ",
    exchange: "NSE",
    token: "3456",
    name: "Tata Motors",
  },
  TATASTEEL: {
    symbol: "TATASTEEL",
    tradingSymbol: "TATASTEEL-EQ",
    exchange: "NSE",
    token: "3499",
    name: "Tata Steel",
  },
  TCS: {
    symbol: "TCS",
    tradingSymbol: "TCS-EQ",
    exchange: "NSE",
    token: "11536",
    name: "Tata Consultancy Services",
  },
  TECHM: {
    symbol: "TECHM",
    tradingSymbol: "TECHM-EQ",
    exchange: "NSE",
    token: "13538",
    name: "Tech Mahindra",
  },
  TITAN: {
    symbol: "TITAN",
    tradingSymbol: "TITAN-EQ",
    exchange: "NSE",
    token: "3506",
    name: "Titan Company",
  },
  TRENT: {
    symbol: "TRENT",
    tradingSymbol: "TRENT-EQ",
    exchange: "NSE",
    token: "1964",
    name: "Trent",
  },
  ULTRACEMCO: {
    symbol: "ULTRACEMCO",
    tradingSymbol: "ULTRACEMCO-EQ",
    exchange: "NSE",
    token: "11532",
    name: "UltraTech Cement",
  },
  WIPRO: {
    symbol: "WIPRO",
    tradingSymbol: "WIPRO-EQ",
    exchange: "NSE",
    token: "3787",
    name: "Wipro",
  },
};

export const NIFTY50_SYMBOLS = Object.keys(INSTRUMENTS);